# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ps1_btn_id = QtWidgets.QPushButton(self.centralwidget)
        self.ps1_btn_id.setGeometry(QtCore.QRect(20, 85, 161, 33))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ps1_btn_id.setFont(font)
        self.ps1_btn_id.setObjectName("ps1_btn_id")
        self.result_text_space = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.result_text_space.setGeometry(QtCore.QRect(20, 270, 331, 251))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.result_text_space.setFont(font)
        self.result_text_space.setReadOnly(True)
        self.result_text_space.setObjectName("result_text_space")
        self.student_result_label = QtWidgets.QLabel(self.centralwidget)
        self.student_result_label.setGeometry(QtCore.QRect(20, 239, 331, 23))
        self.student_result_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.student_result_label.setFont(font)
        self.student_result_label.setText("")
        self.student_result_label.setObjectName("student_result_label")
        self.ps2_btn_id = QtWidgets.QPushButton(self.centralwidget)
        self.ps2_btn_id.setGeometry(QtCore.QRect(190, 85, 161, 33))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ps2_btn_id.setFont(font)
        self.ps2_btn_id.setObjectName("ps2_btn_id")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(370, 21, 900, 501))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.left_list_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.left_list_label.setFont(font)
        self.left_list_label.setText("")
        self.left_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.left_list_label.setObjectName("left_list_label")
        self.gridLayout.addWidget(self.left_list_label, 0, 0, 1, 1)
        self.right_list_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.right_list_label.setFont(font)
        self.right_list_label.setText("")
        self.right_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.right_list_label.setObjectName("right_list_label")
        self.gridLayout.addWidget(self.right_list_label, 0, 1, 1, 1)
        self.left_list = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.left_list.setFont(font)
        self.left_list.setObjectName("left_list")
        self.gridLayout.addWidget(self.left_list, 1, 0, 1, 1)
        self.right_list = QtWidgets.QListWidget(self.layoutWidget)
        self.right_list.setObjectName("right_list")
        self.gridLayout.addWidget(self.right_list, 1, 1, 1, 1)
        self.std_id_input = QtWidgets.QLineEdit(self.centralwidget)
        self.std_id_input.setGeometry(QtCore.QRect(20, 48, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.std_id_input.setFont(font)
        self.std_id_input.setText("")
        self.std_id_input.setObjectName("std_id_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 21, 331, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.ps1_btn_lst = QtWidgets.QPushButton(self.centralwidget)
        self.ps1_btn_lst.setGeometry(QtCore.QRect(20, 195, 161, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ps1_btn_lst.setFont(font)
        self.ps1_btn_lst.setObjectName("ps1_btn_lst")
        self.ps2_btn_lst = QtWidgets.QPushButton(self.centralwidget)
        self.ps2_btn_lst.setGeometry(QtCore.QRect(190, 195, 161, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ps2_btn_lst.setFont(font)
        self.ps2_btn_lst.setObjectName("ps2_btn_lst")
        self.file_input = QtWidgets.QLineEdit(self.centralwidget)
        self.file_input.setGeometry(QtCore.QRect(20, 158, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.file_input.setFont(font)
        self.file_input.setText("")
        self.file_input.setObjectName("file_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 128, 331, 24))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PS1 Eligibility Software"))
        self.ps1_btn_id.setText(_translate("MainWindow", "PS - 1 (from ID)"))
        self.ps2_btn_id.setText(_translate("MainWindow", "PS - 2 (from ID)"))
        self.label.setText(_translate("MainWindow", "Enter Student ID"))
        self.ps1_btn_lst.setText(_translate("MainWindow", "PS - 1 (from list)"))
        self.ps2_btn_lst.setText(_translate("MainWindow", "PS - 2 (from list)"))
        self.label_2.setText(_translate("MainWindow", "Enter file name (with extension)"))
